/control/verbose {verbose}
/control/saveHistory
/run/verbose {verbose}
/tracking/verbose {verbose}

# define the detector geometry

/detector/setFiducialRadius {fiducialRadius}
/detector/setFiducialHeight {fiducialHeight}

/run/initialize

{gpsCommands}

/event/spatialThreshold {spatialThreshold}
/event/timeThreshold {timeThreshold}

/random/setSeeds {randomSeed1} {randomSeed2}

# output filename
/run/setOutputFileName {outputFileName}

/run/printProgress {printProgress}
/run/beamOn {beamOn}
