#include "SensitiveDetector.hh"
#include "G4HCofThisEvent.hh"
#include "G4Step.hh"
#include "G4SDManager.hh"
#include "G4ios.hh"
#include "G4SystemOfUnits.hh"
#include "G4PhysicalConstants.hh"
#include "G4ThreeVector.hh"
#include "G4VProcess.hh"
#include "Hit.hh"

/**
 * @namespace G4Sim
 * @brief Namespace for the G4Sim library.
/*/
namespace G4Sim {

/**
 * @brief Constructs a SensitiveDetector object.
 * 
 * @param name The name of the SensitiveDetector.
 * @param hitsCollectionName The name of the hits collection.
 */
SensitiveDetector::SensitiveDetector(const G4String& name, const G4String& hitsCollectionName)
    : G4VSensitiveDetector(name), fHitsCollection(nullptr), fHitsCollectionID(-1), fTotalEnergyDeposit(0.) {
    collectionName.insert(hitsCollectionName);
}

SensitiveDetector::~SensitiveDetector() {}

/**
 * @brief Initialize the SensitiveDetector.
 * 
 * This function is called to initialize the SensitiveDetector. It creates a new HitsCollection
 * and assigns it to the SensitiveDetector. It also retrieves the collection ID and adds the
 * HitsCollection to the G4HCofThisEvent object. Finally, it resets the total energy deposit.
 * 
 * @param hce Pointer to the G4HCofThisEvent object.
 */
void SensitiveDetector::Initialize(G4HCofThisEvent* hce) {
    
    fHitsCollection = new HitsCollection(SensitiveDetectorName, collectionName[0]);
    if (fHitsCollectionID < 0) {
        fHitsCollectionID = G4SDManager::GetSDMpointer()->GetCollectionID(fHitsCollection);
    }
    //fHitsCollection = new G4THitsCollection<Hit>(SensitiveDetectorName, collectionName[0]);

    G4int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
    hce->AddHitsCollection(hcID, fHitsCollection);
    fTotalEnergyDeposit = 0.;  // Reset total energy deposit

}

/**
 * ProcessHits function is responsible for processing the hits generated by particles in the sensitive detector.
 * It calculates the energy deposit, creates a new hit object, and sets the relevant properties of the hit.
 * The hit object is then inserted into the hits collection and the total energy deposit is accumulated.
 * 
 * @param step A pointer to the G4Step object representing the step taken by the particle.
 * @param history A pointer to the G4TouchableHistory object representing the touchable history of the step.
 * @return A boolean value indicating whether the hit was processed successfully or not.
 */
G4bool SensitiveDetector::ProcessHits(G4Step* step, G4TouchableHistory*) {
    G4double edep = step->GetTotalEnergyDeposit();
    if (edep == 0.) return false;

    G4Sim::Hit* newHit = new G4Sim::Hit();
    //Hit* newHit = new Hit();
    newHit->energyDeposit = edep;
    //newHit->position = step->GetPreStepPoint()->GetPosition();
    newHit->position = step->GetPostStepPoint()->GetPosition();
    newHit->time = step->GetPostStepPoint()->GetGlobalTime();
    newHit->trackID = step->GetTrack()->GetTrackID();
    newHit->parentID = step->GetTrack()->GetParentID();
    newHit->momentum = step->GetPreStepPoint()->GetMomentum();
    newHit->particleType = step->GetTrack()->GetDefinition()->GetParticleName();
    newHit->processType = step->GetPostStepPoint()->GetProcessDefinedStep()->GetProcessName();
    newHit->particleEnergy0 = step->GetPreStepPoint()->GetKineticEnergy();
    newHit->particleEnergy1 = step->GetPostStepPoint()->GetKineticEnergy(); 

    
    //if (newHit->trackID == 1){
    //    newHit->Print();
    //    // get the track energy before the step
    //    G4cout << newHit->processType<<" SensitiveDetector::ProcessHits: track energy before: " << step->GetPreStepPoint()->GetKineticEnergy() / keV << " keV"<<G4endl;
    //    G4cout << newHit->processType<<" SensitiveDetector::ProcessHits: track energy after: " << step->GetTrack()->GetKineticEnergy() / keV << " keV" <<G4endl;
    //}

    fHitsCollection->insert(newHit);
    fTotalEnergyDeposit += edep;  // Accumulate total energy deposit

    return true;
}

/**
 * @brief This function is called at the end of each event in the SensitiveDetector class.
 * It processes the hits collected during the event and performs any necessary calculations or actions.
 * 
 * @param hce A pointer to the G4HCofThisEvent object containing the hits collections.
 */
void SensitiveDetector::EndOfEvent(G4HCofThisEvent* hce) {
    if (!fHitsCollection) return;

    // Example of processing hits at the end of the event
    G4int numHits = fHitsCollection->entries();
    //G4cout << "End of event: total energy deposited in sensitive detector: "
    //       << fTotalEnergyDeposit / CLHEP::MeV << " MeV" << G4endl;
}

} // namespace G4Sim
